apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = AKIAVQ3EAAN6Z3QR4WWY
    aws_secret_access_key = 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
