apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: souaibou1618/backend-feed:v1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: env-pg-secrets
            - configMapRef:
                name: env-configmap
          volumeMounts:
            - mountPath: "/root/.aws/"
              name: aws-creds
      volumes:
        - name: aws-creds
          configMap:
            name: aws-creds
